# This playbook installs all dva prerequsites and then installs dva itself. It is intended for RHEL 7.
---
- hosts: RHEL
  tasks:
    - name: Adding PyPA repo to get newer version of python-setuptools
      become: true
      yum_repository:
        name: pypa-pypa
        description: Copr repo for pypa
        baseurl: https://copr-be.cloud.fedoraproject.org/results/pypa/pypa/epel-7-$basearch/
        gpgcheck: no
        gpgkey: https://copr-be.cloud.fedoraproject.org/results/pypa/pypa/pubkey.gpg
        enabled: yes
      
    - name: Install required packages
      become: true
      package: name={{ item }} state=present
      with_items: 
        - python-devel
        - gcc
        - libffi-devel
        - openssl-devel
        - git
        - python-pip

    - name: Upgrade pip 
      become: true
      command: pip install --upgrade pip

    - name: Install pip dependencies
      become: true
      command: pip install {{ item }}
      with_items: 
        - aaargh
        - boto
        - gevent
        - stitches
        - setuptools
      
    - name: clone dva
      git:
        repo: https://github.com/RedHatQE/dva.git
        dest: /home/ec2-user/dva
      
    - name: temporary hack - replace old gevent.coros method name
      command: find /home/ec2-user/dva -type f -name '*py' -exec sed -i 's/gevent\.coros/gevent\.lock/g' {} \;
     
    - name: install dva
      become: true
      shell: python setup.py install
      args:
        chdir: /home/ec2-user/dva
        creates: dva_installation_log.txt
 
      